// <auto-generated />
using System;
using FunderMaps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FunderMaps.Data.Migrations
{
    [DbContext(typeof(FunderMapsDbContext))]
    [Migration("00000000000001_CreateFunderMapsSchema")]
    partial class CreateFunderMapsSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            //
        }
    }
}
