using Bogus;
using FunderMaps.Core.Entities;

namespace FunderMaps.IntegrationTests.Faker
{
    /// <summary>
    ///     Faker for <see cref="User"/>.
    /// </summary>
    public class UserFaker : Faker<User>
    {
        public static readonly IEnumerable<string> jobs = new List<string>
        {
            "accountant",
            "actor",
            "air steward",
            "animator",
            "architect",
            "assistant",
            "author",
            "baker",
            "biologist",
            "builder",
            "butcher",
            "career counselor",
            "caretaker",
            "chef",
            "civil servant",
            "clerk",
            "comic book writer",
            "company director",
            "programmer",
            "cook",
            "decorator",
            "dentist",
            "designer",
            "diplomat",
            "director",
            "doctor",
            "economist",
            "editor",
            "electrician",
            "engineer",
            "executive",
            "farmer",
            "film director",
            "fisherman",
            "fishmonger",
            "flight attendant",
            "garbage man",
            "geologist",
            "hairdresser",
            "head teacher",
            "jeweler",
            "journalist",
            "judge",
            "juggler",
            "lawyer",
            "lecturer",
            "lexicographer",
            "library assistant",
            "magician",
            "makeup artist",
            "manager",
            "miner",
            "musician",
            "nurse",
            "optician",
            "painter",
            "personal assistant",
            "photographer",
            "pilot",
            "plumber",
            "police officer",
            "politician",
            "porter",
            "printer",
            "prison officer / warder",
            "professional gambler",
            "puppeteer",
            "receptionist",
            "sailor",
            "salesperson",
            "scientist",
            "secretary",
            "shop assistant",
            "sign language Interpreter",
            "singer",
            "soldier",
            "solicitor",
            "surgeon",
            "tailor",
            "teacher",
            "telephone operator",
            "telephonist",
            "translator",
            "travel agent",
            "trucker",
            "TV cameraman",
            "TV presenter",
            "vet",
            "waiter",
            "web designer",
            "writer",
        };
    }
}
