name: FunderMaps Ecosystem

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop

env:
  DOTNET_VERSION: '5.0'
  BUILD_CONFIG: Release

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis
        ports:
          - 5432:5432

        env:
          POSTGRES_PASSWORD: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Setup database
      run: |
        psql -d postgres -c "CREATE DATABASE fundermaps"
        psql -c "CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public"
        psql -c "CREATE EXTENSION IF NOT EXISTS uuid-ossp WITH SCHEMA public"
        psql < database/fundermaps.sql
      env:
        PGDATABASE: fundermaps
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres

    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: Install dependencies
      run: dotnet restore

    - name: Print version
      run: |
        find src -type f -exec sed -i "s/@@VERSION@@/$(git describe --long --always)/" {} +
        find src -type f -exec sed -i "s/@@COMMIT@@/$(git rev-parse HEAD)/" {} +

    - name: Build
      run: dotnet build --nologo --configuration ${{ env.BUILD_CONFIG }} --no-restore

    - name: Test
      run: dotnet test --nologo --configuration ${{ env.BUILD_CONFIG }} --no-restore
      env:
        Jwt__Issuer: "FunderMapsTest"
        Jwt__Audience: "FunderMapsTest"
        Jwt__TokenValidity: 10
        Jwt__SignatureKey: somelargetextstringusedinsignatures
