name: FunderMaps Package Outdated

on:
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: '5.0'

jobs:
  build:
    name: List outdated packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore --no-cache --force-evaluate

    - name: Check package dependencies
      run: dotnet list package --outdated
