name: FunderMaps Ecosystem

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '3.1.101'
  BUILD_CONFIG: Release
  ARCHIVE_BACKEND: backend-dist.${{ github.sha }}.tar.gz
  ARCHIVE_WEBSERVICE: webservice-dist.${{ github.sha }}.tar.gz

jobs:
  build:
    if: github.ref == 'refs/heads/_placeholder'
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --nologo --configuration ${{ env.BUILD_CONFIG }} --no-restore
    - name: Test
      run: dotnet test --nologo --no-restore
  
  publish:
    name: Publish
    needs: build
#     if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: Install dependencies
      run: dotnet restore

    - name: Publish FunderMaps.WebApi
      run: dotnet publish src/FunderMaps.WebApi --nologo --configuration ${{ env.BUILD_CONFIG }} --output backend-dist

    - name: Create archive
      run: tar -czf backed.tar.gz -C backend-dist .

    - name: Publish FunderMaps.Webservice
      run: dotnet publish src/FunderMaps.Webservice --nologo --configuration ${{ env.BUILD_CONFIG }} --output webservice-dist

    - name: Create archive
      run: tar -czf ${{ env.ARCHIVE_WEBSERVICE }} -C webservice-dist .

    - name: Copy archive via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: 'backed.tar.gz'
        target: '/tmp/'
