name: FunderMaps Package Outdated

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  DOTNET_VERSION: '3.1.101'

jobs:
  build:
    name: List outdated packages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    - name: Check package dependencies
      run: dotnet list package --outdated
