name: FunderMaps Docker Container

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build --build-arg subtool=FunderMaps.WebApi .

