name: FunderMaps Docker Containers

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subtool:
          - FunderMaps.WebApi
          - FunderMaps.Webservice
          - FunderMaps.BatchNode
          - FunderMaps.Portal
          - FunderMaps.Cli

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build --build-arg subtool=${{ matrix.subtool }} .
